Repository eclipse-edc/Samples, pull requests merged in 2023-12, with the labels that each got.

#176 build: Dependency Correction on Cloud Transfer Sample
  transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts
  transfer/transfer-05-file-transfer-cloud/transfer-file-cloud/build.gradle.kts
Labels: bug

#165 docs: improve readability of documentation
  advanced/advanced-01-open-telemetry/README.md
  advanced/advanced-01-open-telemetry/resources/get-dataset.json
  advanced/advanced-01-open-telemetry/resources/negotiate-contract.json
  advanced/advanced-01-open-telemetry/resources/start-transfer.json
  basic/basic-02-health-endpoint/README.md
  system-tests/src/test/java/org/eclipse/edc/samples/advanced/Advanced01openTelemetryTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/common/NegotiationCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer01negotiationTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/util/TransferUtil.java
  transfer/streaming/streaming-01-http-to-http/README.md
  transfer/streaming/streaming-02-kafka-to-http/1-asset.json
  transfer/streaming/streaming-02-kafka-to-http/README.md
  transfer/streaming/streaming-03-kafka-broker/README.md
  transfer/transfer-01-negotiation/README.md
  transfer/transfer-01-negotiation/resources/get-dataset.json
  transfer/transfer-01-negotiation/resources/negotiate-contract.json
  transfer/transfer-02-consumer-pull/README.md
  transfer/transfer-02-consumer-pull/resources/start-transfer.json
  transfer/transfer-03-provider-push/resources/start-transfer.json
  transfer/transfer-04-event-consumer/README.md
  util/http-request-logger/build.gradle.kts
Labels: documentation

#180 refactor: move custom-runtime under advanced folder
  advanced/advanced-02-custom-runtime/build.gradle.kts
  advanced/advanced-02-custom-runtime/src/main/java/org/eclipse/edc/sample/runtime/CustomRuntime.java
  basic/basic-01-basic-connector/README.md
  settings.gradle.kts
Labels: refactoring
