Repository eclipse-edc/Samples, pull requests merged in 2023-10, with the labels that each got.

#128 fix: #86 sample 04 terminating on startup
  .github/workflows/verify.yaml
  gradle/libs.versions.toml
  system-tests/build.gradle.kts
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/FileTransferSampleTestCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04openTelemetryTest.java
  transfer/transfer-04-open-telemetry/README.md
  transfer/transfer-04-open-telemetry/contractoffer.json
  transfer/transfer-04-open-telemetry/docker-compose.yaml
  transfer/transfer-04-open-telemetry/filetransfer.json
  transfer/transfer-04-open-telemetry/input-file.txt
  transfer/transfer-04-open-telemetry/open-telemetry-consumer/build.gradle.kts
  transfer/transfer-04-open-telemetry/open-telemetry-provider/build.gradle.kts
Labels: bug, refactoring

#132 refactor: building connector jars for telemetry end to end test from docker compose file
  .github/workflows/verify.yaml
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/FileTransferSampleTestCommon.java
  transfer/transfer-04-open-telemetry/README.md
  transfer/transfer-04-open-telemetry/docker-compose.yaml
  transfer/transfer-04-open-telemetry/filetransfer.json
  transfer/transfer-04-open-telemetry/open-telemetry-consumer/Dockerfile
  transfer/transfer-04-open-telemetry/open-telemetry-consumer/build.gradle.kts
  transfer/transfer-04-open-telemetry/open-telemetry-provider/Dockerfile
  transfer/transfer-04-open-telemetry/open-telemetry-provider/build.gradle.kts
Labels: bug

#134 fix: add missing edc-control-plane-api-client dependency
  transfer/transfer-06-consumer-pull-http/http-pull-connector/build.gradle.kts
Labels: bug

#137 docs: consumer-pull transfer README update
  transfer/transfer-06-consumer-pull-http/README.md
Labels: documentation

#138 fix: add missing edc-control-plane-api-client dependency (#134)
  transfer/transfer-07-provider-push-http/README.md
  transfer/transfer-07-provider-push-http/http-push-connector/build.gradle.kts
Labels: bug
