Repository eclipse-edc/Samples, pull requests merged in 2023-11, with the labels that each got.

#149 docs: fix invalid command line in the README of transfer-00-prerequisites
  transfer/transfer-00-prerequisites/README.md
Labels: bug

#145 fix(docs): change contributing.md link to correct one
  CONTRIBUTING.md
  README.md
Labels: documentation

#151 feat: provide kafka-broker transfer streaming sample
  .github/workflows/verify.yaml
  gradle/libs.versions.toml
  settings.gradle.kts
  system-tests/build.gradle.kts
  system-tests/src/test/java/org/eclipse/edc/samples/common/FileTransferCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/KafkaSaslContainer.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming03KafkaToKafkaTest.java
  transfer/streaming/streaming-03-kafka-broker/1-asset.json
  transfer/streaming/streaming-03-kafka-broker/2-policy-definition.json
  transfer/streaming/streaming-03-kafka-broker/3-contract-definition.json
  transfer/streaming/streaming-03-kafka-broker/4-get-dataset.json
  transfer/streaming/streaming-03-kafka-broker/5-negotiate-contract.json
  transfer/streaming/streaming-03-kafka-broker/6-transfer.json
  transfer/streaming/streaming-03-kafka-broker/README.md
  transfer/streaming/streaming-03-kafka-broker/kafka-config/admin.properties
  transfer/streaming/streaming-03-kafka-broker/kafka.env
  transfer/streaming/streaming-03-kafka-broker/kafka_broker_jaas.conf
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/build.gradle.kts
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/consumer.properties
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/provider.properties
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/java/org/eclipse/edc/samples/streaming/KafkaExtension.java
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/java/org/eclipse/edc/samples/streaming/KafkaToKafkaDataFlowController.java
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
Labels: enhancement

#155 fix(docs): fix some typos
  transfer/transfer-00-prerequisites/README.md
  transfer/transfer-01-negotiation/README.md
  transfer/transfer-02-consumer-pull/README.md
  transfer/transfer-04-event-consumer/README.md
Labels: documentation
