Repository eclipse-edc/Samples, pull requests merged in 2023-07, with the labels that each got.

#79 feat: enable dependabot
  .github/dependabot.yml
Labels: enhancement

#85 build(deps): Bump edc to 0.1.3
  .github/workflows/scan-pull-request.yml
  gradle/libs.versions.toml
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/FileTransferSampleTestCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer03modifyTransferProcessTest.java
  transfer/transfer-01-file-transfer/filetransfer.json
  transfer/transfer-03-modify-transferprocess/simulator/src/main/java/org/eclipse/edc/sample/extension/transfer/TransferSimulationExtension.java
  transfer/transfer-06-consumer-pull-http/README.md
  transfer/transfer-07-provider-push-http/README.md
Labels: dependencies

#90 docs: update readme to correspond to latest Dataplane Selector API
  transfer/transfer-06-consumer-pull-http/README.md
  transfer/transfer-07-provider-push-http/README.md
Labels: documentation, stale
