Repository eclipse-edc/Samples, pull requests merged in 2024-03, with the labels that each got.

#217 build(deps): bump EDC to 0.5.1
  advanced/advanced-01-open-telemetry/docker-compose.yaml
  advanced/advanced-01-open-telemetry/open-telemetry-consumer/Dockerfile
  advanced/advanced-01-open-telemetry/open-telemetry-provider/Dockerfile
  advanced/advanced-01-open-telemetry/open-telemetry-provider/build.gradle.kts
  advanced/advanced-01-open-telemetry/open-telemetry-runtime/Dockerfile
  advanced/advanced-01-open-telemetry/open-telemetry-runtime/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  policy/policy-01-policy-enforcement/resources/contract-request.json
  policy/policy-01-policy-enforcement/resources/create-policy.json
  settings.gradle.kts
  system-tests/build.gradle.kts
  system-tests/src/test/java/org/eclipse/edc/samples/advanced/Advanced01openTelemetryTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/common/PrerequisitesCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer02consumerPullTest.java
  transfer/streaming/streaming-01-http-to-http/streaming-01-runtime/build.gradle.kts
  transfer/streaming/streaming-02-kafka-to-http/5-negotiate-contract.json
  transfer/streaming/streaming-02-kafka-to-http/streaming-02-runtime/build.gradle.kts
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/build.gradle.kts
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/src/main/java/org/eclipse/edc/samples/streaming/KafkaToKafkaDataFlowController.java
  transfer/transfer-00-prerequisites/connector/build.gradle.kts
  transfer/transfer-01-negotiation/resources/create-policy.json
  transfer/transfer-04-event-consumer/consumer-with-listener/build.gradle.kts
  transfer/transfer-05-file-transfer-cloud/transfer-file-cloud/build.gradle.kts
Labels: dependencies

#225 docs: updated README.md for transfer-02-consumer-pull
  transfer/transfer-02-consumer-pull/README.md
Labels: documentation, stale

#232 fix: update description about required Java version
  README.md
  advanced/advanced-01-open-telemetry/README.md
Labels: bug, documentation
