Repository eclipse-edc/Samples, pull requests merged in 2024-08, with the labels that each got.

#302 build(deps): bump EDC to 0.8.1
  gradle/libs.versions.toml
  system-tests/src/test/java/org/eclipse/edc/samples/basic/Basic02healthEndpointTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/basic/Basic03configurationTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/common/PrerequisitesCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer01negotiationTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer02consumerPullTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer03providerPushTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer04eventConsumerTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming01httpToHttpTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming02KafkaToHttpTest.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/streaming/Streaming03KafkaToKafkaTest.java
  transfer/streaming/streaming-01-http-to-http/streaming-01-runtime/consumer.properties
  transfer/streaming/streaming-01-http-to-http/streaming-01-runtime/provider.properties
  transfer/streaming/streaming-02-kafka-to-http/streaming-02-runtime/consumer.properties
  transfer/streaming/streaming-02-kafka-to-http/streaming-02-runtime/provider.properties
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/consumer.properties
  transfer/streaming/streaming-03-kafka-broker/streaming-03-runtime/provider.properties
Labels: dependencies

#307 fix: add dependency to keep runtime alive
  basic/basic-01-basic-connector/build.gradle.kts
Labels: bug

#297 feat: add support for minio and azurite for cloud sample
  gradle/libs.versions.toml
  system-tests/build.gradle.kts
  system-tests/src/test/java/org/eclipse/edc/samples/common/FileTransferCloudCommon.java
  system-tests/src/test/java/org/eclipse/edc/samples/transfer/Transfer05fileTransferCloudTest.java
  transfer/transfer-05-file-transfer-cloud/README.md
  transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/build.gradle.kts
  transfer/transfer-05-file-transfer-cloud/cloud-transfer-consumer/config.properties
  transfer/transfer-05-file-transfer-cloud/cloud-transfer-provider/build.gradle.kts
  transfer/transfer-05-file-transfer-cloud/cloud-transfer-provider/config.properties
  transfer/transfer-05-file-transfer-cloud/resources/docker-compose.yaml
  transfer/transfer-05-file-transfer-cloud/resources/fetch-catalog.json
  transfer/transfer-05-file-transfer-cloud/resources/get-dataset.json
  transfer/transfer-05-file-transfer-cloud/resources/negotiate-contract.json
  transfer/transfer-05-file-transfer-cloud/resources/start-transfer.json
  transfer/transfer-05-file-transfer-cloud/resources/test-document.txt
  transfer/transfer-05-file-transfer-cloud/terraform/aws.tf
  transfer/transfer-05-file-transfer-cloud/terraform/main.tf
  transfer/transfer-05-file-transfer-cloud/terraform/output.tf
  transfer/transfer-05-file-transfer-cloud/terraform/test-document.txt
  transfer/transfer-05-file-transfer-cloud/terraform/variables.tf
  transfer/transfer-05-file-transfer-cloud/transfer-file-cloud/src/main/java/org/eclipse/edc/sample/extension/transfer/CloudTransferExtension.java
Labels: enhancement
